### ISSUE TITLE
Can't compile in Mars

### ISSUE THREAD

**Issue by akurtakov** [iloveeclipse/anyedittools#109]
When importing and trying to build in Eclipse 4.5 AnyEdit can't be compiled due to org.eclipse.ui.internal.SaveAllAction and org.eclipse.ui.internal.SaveAction being removed.

**Comment by iloveeclipse** [comment]
This is expected, since Anyedit still supports Eclipse 3.6. 
Anyedit should be compiled against 3.6 SDK - it is OK for 3.6 and higher Eclipse.
