### ISSUE TITLE
No longer builds against Eclipse 4.5.1

### ISSUE THREAD

**Issue by mbooth101** [iloveeclipse/anyedittools#110]
Since this commit: http://git.eclipse.org/c/platform/eclipse.platform.ui.git/commit/?id=8369880848f32e6e6580f6b72d0ea644f41a2c4c

AnyEdit no longer builds since it relies on the internal "SaveAction" class and that has been removed.

**Comment by iloveeclipse** [comment]
Yea. The code which uses SaveAction is for older Eclipse platforms (3.6), so probably I can remove it some time later, this is not that urgent. The easy workaround is to compile against 4.5 or 4.4.

**Comment by mbooth101** [comment]
Okay, great. In Fedora Linux we only have 4.5.1, so I guess it is safe to delete this code in a downstream patch for now.

**Comment by iloveeclipse** [comment]
If you are going to delete it, delete StartupHelper, SpecialSaveAction and SpecialSaveAllAction. You will need to update AnyeditStartup code accordingly, but this should be a no-brainer. If you do so, please also provide pull request so that I can integrate it later. Thanks.

**Comment by mbooth101** [comment]
Will do, thanks for the hints! :-)

**Comment by mbooth101** [comment]
See PR #112 -- this seems to work for me
