### ISSUE TITLE
AnyEdit does not work at all

### ISSUE THREAD

**Issue by xerces8** [iloveeclipse/anyedittools#115]
I updated AnyEdit from previous version to 2.6.0 and it does not work at all.
There is no trace of it in Preferences or in the context menus.

I have Eclipse 4.3.2 (Kepler SR-2).

I also uninstalled AnyEdit and reinstalled it (from the marketplace).
Same results.
AnyEdit is listed in About / Installation details, but does not work at all.

**Comment by iloveeclipse** [comment]
AnyEdit requires Java 7 now.

**Comment by xerces8** [comment]
I use Java 8.

Are there any logs or similar that I can look for clues?

**Comment by xerces8** [comment]
Sorry, I used 1.6 *
With Java 8 it works.

* for some reason the Preferences / Java / Installed JREs dialog showed
only Java 8 when I checked, even if Eclipse was running under Java 1.6. Now
it whows both 1.6 and 8.
