### ISSUE TITLE
Additional compare options under "Compare With" not appearing

### ISSUE THREAD

**Issue by pelowe** [iloveeclipse/anyedittools#116]
Aptana standalone v3.6.0
Eclipse v4.3.2
Anyedit v2.6.1
Windows 7

Screenshot should show the problem in v2.6.1:
![image](https://cloud.githubusercontent.com/assets/11821990/13177859/b9a38bd8-d6e9-11e5-99de-2ab37c734905.png)

Screenshot showing the desired behavior that worked in v2.4.15:
![image](https://cloud.githubusercontent.com/assets/11821990/13178063/f29ac770-d6ea-11e5-881f-758b23502e0c.png)

Just to note, I have the same setup on a Windows 10 machine that works fine. So it may be a OS related issue.

Config: [Eclipse_config.txt](https://github.com/iloveeclipse/anyedittools/files/138094/Eclipse_config.txt)

Thanks
Perry

**Comment by iloveeclipse** [comment]
It is probably Java related - on your Windows 7 machine you probably have Java 6, and on Windows 10 Java 7+. Anyedit requires now Java 7.

**Comment by pelowe** [comment]
Thank Andrey. I was able to upgrade to Java 8 and now it works.
