### ISSUE TITLE
Disallow AnyEditTool from converting Spaces into Tabs for YAML files

### ISSUE THREAD

**Issue by BoykoAlex** [iloveeclipse/anyedittools#118]
The syntax of YAML forbids to use tabs for indentation. One could always go into Preferences and add it to the list of excluded files, but is there any chance to make *.yml files excluded by default?

**Comment by iloveeclipse** [comment]
Feel free to provide a pull request. You must change https://github.com/iloveeclipse/anyedittools/blob/master/AnyEditTools/src/de/loskutov/anyedit/ui/preferences/AndyEditPreferenceInitializer.java

**Comment by BoykoAlex** [comment]
Here it is :-)
https://github.com/iloveeclipse/anyedittools/pull/119

**Comment by iloveeclipse** [comment]
Thanks. The patch will be in some future release (not planned yet).

**Comment by BoykoAlex** [comment]
Is this fix going to be available in some snapshot build? Was looking around checking if there is an update site for AnyEditTool snapshot/integration builds available, but didn't find anything.
