### ISSUE TITLE
RFE: Put the word "sort" in the sorting actions

### ISSUE THREAD

**Issue by arantius** [iloveeclipse/anyedittools#120]
I used SortIt for a long time (but it broke when I upgraded Eclipse).  Then I realized AnyEdit does sorting when I looked for another plugin.  I'm used to typing `Ctrl+3 sort <Enter>` but the word "sort" is not in the menu items that AnyEdit exposes (it's in the menu that contains them), so they don't show up.

Being able to quick search for the word sort and find the sorting features would be a nice enhancement.

**Comment by iloveeclipse** [comment]
Done. If I will find some free time in this life I will push a new version to the update site.
