### ISSUE TITLE
eclipse stuck memory leak - caused by AnyEdit

### ISSUE THREAD

**Issue by yevshif** [iloveeclipse/anyedittools#121]
Please refer to https://bugs.eclipse.org/bugs/show_bug.cgi?id=453163 for details.

**Comment by iloveeclipse** [comment]
I've commented in bugzilla, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=453163#c29

TL;DR: if CDT has memory issues, it is nothing I can/will fix in AnyEdit.
