### ISSUE TITLE
AnyEdit causes the line break indicators to be colored inconsistently

### ISSUE THREAD

**Issue by j-ulrich** [iloveeclipse/anyedittools#135]
After installing AnyEdit, the line break indicators are colored strangely:

<img width="880" alt="Incorrect line break coloring" src="https://user-images.githubusercontent.com/1260380/70156304-04e0ff00-16b4-11ea-88ba-fcaab88d23d7.png">

- If the first line which is currently visible ends with a comment, all line break indicators are colored in the color of that comment.
- If I scroll the view, the line break indicators change their color depending on whether the first visible line ends with a comment or not.
- If I put the cursor on one line, the line break indicator of that line changes its color to the default color.
- If I select a variable and have "Mark Occurrences" enabled, all lines between the first and the last occurrence of the variable change the color of their line break indicator to the default color.
- When I switch the foreground application to another application and back to Eclipse again, all line break indicators are colored according to the first visible line again.

In previous versions of Eclipse I could get rid of this behavior by disabling the "Color trailing whitespace differently" feature.
However, I just installed Eclipse 2019-09 and now this coloring behavior stays even if I disable the "Color trailing whitespace differently" feature. ☹️

**Comment by j-ulrich** [comment]
Also note that the "Color trailing whitespace differently" feature itself doesn't seem to work anymore.

**Comment by iloveeclipse** [comment]
1) I can't reproduce, neither wrong color nor not working "Color trailing whitespace differently".
2) AnyEdit doesn't change / touch the color of line end characters.
3) Please check error log if there is something reported.
4) The syntax color looks different to what I see on default C++ editor. Is this somehow customized?
5) If this happens in C++ files only, please open bug for Eclipse CDT.

**Comment by j-ulrich** [comment]
Oh you're right! It also happens without AnyEdit tools.
I always thought it was related to AnyEdit Tools because the behavior vanished after disabling the "Color trailing whitespace differently" feature.
