### ISSUE TITLE
Word wrap margin

### ISSUE THREAD

**Issue by webmdb531** [iloveeclipse/anyedittools#140]
For Toggle Word Wrap it would be great to be able to set the right margin or line length for text files other than code. This functionality would mirror line length settings for code files.

**Comment by iloveeclipse** [comment]
DOn't get me wrong, but this functionality is not provided by my plugin, but be platform.
Feel free to file the bug in https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform
